// Auto-generated by SaaG (Software as a Graph)
// Scenario: Happy Path: Valid Login
// Conforms to RFC-003 Dataflow Verification Specification

import Testing
import Foundation
@testable import AuthSample

@Suite("SaaG Dataflow: Happy Path: Valid Login")
struct SaagGeneratedDataflowTests {

    @Test("Verifies end-to-end dataflow and node state transitions")
    @MainActor
    func testDataflow() async throws {
        // 1. Initial State & Component Graph Setup
        let mockService = LiveAuthService()
        let storage = KeychainStorage()
        let viewModel = AuthViewModel(authService: mockService, tokenStorage: storage)

        // 2. Input Injection at Port: login(credentials:)
        let inputPayload = Credentials(email: "alban@example.com", password: "password123")
        await viewModel.login(credentials: inputPayload)

        // 3. Node State Assertions derived from Graph Trace
        #expect(viewModel.isLoading == false, "ViewModel should finish in non-loading state")
        #expect(viewModel.errorMessage == nil, "No error message should be present on success")
        #expect(viewModel.activeSession != nil, "Active user session must be populated")
        #expect(viewModel.activeSession?.userId == "user_mock_42")

        // 4. Downstream Storage Node Assertion
        let savedToken = await storage.retrieve()
        #expect(savedToken == "jwt_mock_token_abc123", "KeychainStorage must contain the persisted session token")
    }
}