import React, { useState } from 'react';
import { X, Copy, Check, Download, FileCode, CheckCircle2 } from 'lucide-react';

export default function ExportTestModal({ isOpen, onClose, simulation, graph }) {
  if (!isOpen) return null;

  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const scenarioName = simulation?.title || 'Dataflow Verification';

  const projectName = (graph?.metadata?.projectName || '').toLowerCase();
  const isLandmarks = projectName.includes('landmark') || Boolean(graph?.nodes?.node_landmarksapp);
  const isMakeItSo = projectName.includes('makeitso') || Boolean(graph?.nodes?.node_makeitsoapp);

  let targetPath = 'examples/ios-auth-sample/Tests/AuthSampleTests/GeneratedDataflowTests.swift';
  let generatedCode = '';

  if (isLandmarks) {
    targetPath = 'benchmarks/Landmarks/LandmarksTests/GeneratedDataflowTests.swift';
    generatedCode = `// Auto-generated by SaaG (Software as a Graph)
// Scenario: ${scenarioName}
// Conforms to RFC-003 Dataflow Verification Specification

import Testing
import Foundation
@testable import Landmarks

@Suite("SaaG Dataflow: ${scenarioName}")
struct LandmarksGeneratedDataflowTests {

    @Test("Verifies end-to-end dataflow and ModelData state transitions")
    @MainActor
    func testDataflow() async throws {
        // 1. Initial State & Component Graph Setup
        let modelData = ModelData()
        let initialIndex = 0
        let landmarkId = modelData.landmarks[initialIndex].id
        let initialFavorite = modelData.landmarks[initialIndex].isFavorite

        // 2. Input Injection at Port: onUserAction (FavoriteButton)
        modelData.landmarks[initialIndex].isFavorite.toggle()

        // 3. Node State Assertions derived from Graph Trace
        #expect(modelData.landmarks[initialIndex].isFavorite != initialFavorite, "Favorite status must toggle")
        #expect(modelData.landmarks.first(where: { $0.id == landmarkId })?.isFavorite == !initialFavorite)
    }
}`;
  } else if (isMakeItSo) {
    targetPath = 'benchmarks/MakeItSo/code/frontend/MakeItSo/Shared/GeneratedDataflowTests.swift';
    generatedCode = `// Auto-generated by SaaG (Software as a Graph)
// Scenario: ${scenarioName}
// Conforms to RFC-003 Dataflow Verification Specification

import Testing
import Foundation
@testable import MakeItSo

@Suite("SaaG Dataflow: ${scenarioName}")
struct MakeItSoGeneratedDataflowTests {

    @Test("Verifies reminder creation and repository persistence")
    @MainActor
    func testDataflow() async throws {
        // 1. Initial State & Component Graph Setup
        let repository = RemindersRepository()
        let viewModel = RemindersListViewModel(remindersRepository: repository)
        let initialCount = viewModel.reminders.count

        // 2. Input Injection at Port: onUserAction (ReminderDetailsView)
        let newReminder = Reminder(title: "Review SaaG architecture graph", isCompleted: false)
        viewModel.createReminder(newReminder)

        // 3. Node State Assertions derived from Graph Trace
        #expect(viewModel.reminders.count == initialCount + 1, "Reminder list count should increment")
    }
}`;
  } else {
    targetPath = 'examples/ios-auth-sample/Tests/AuthSampleTests/GeneratedDataflowTests.swift';
    generatedCode = `// Auto-generated by SaaG (Software as a Graph)
// Scenario: ${scenarioName}
// Conforms to RFC-003 Dataflow Verification Specification

import Testing
import Foundation
@testable import AuthSample

@Suite("SaaG Dataflow: ${scenarioName}")
struct SaagGeneratedDataflowTests {

    @Test("Verifies end-to-end dataflow and node state transitions")
    @MainActor
    func testDataflow() async throws {
        // 1. Initial State & Component Graph Setup
        let mockService = LiveAuthService()
        let storage = KeychainStorage()
        let viewModel = AuthViewModel(authService: mockService, tokenStorage: storage)

        // 2. Input Injection at Port: login(credentials:)
        let inputPayload = Credentials(email: "alban@example.com", password: "password123")
        await viewModel.login(credentials: inputPayload)

        // 3. Node State Assertions derived from Graph Trace
        #expect(viewModel.isLoading == false, "ViewModel should finish in non-loading state")
        #expect(viewModel.errorMessage == nil, "No error message should be present on success")
        #expect(viewModel.activeSession != nil, "Active user session must be populated")
        #expect(viewModel.activeSession?.userId == "user_mock_42")

        // 4. Downstream Storage Node Assertion
        let savedToken = await storage.retrieve()
        #expect(savedToken == "jwt_mock_token_abc123", "KeychainStorage must contain the persisted session token")
    }
}`;
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveToSuite = async () => {
    setIsSaving(true);
    try {
      const res = await fetch('/api/save-test', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: generatedCode, targetPath })
      });
      if (!res.ok) throw new Error('Failed saving test');
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (e) {
      alert('Error saving test: ' + e.message);
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card glass-panel" style={{ width: 680 }} onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <FileCode size={20} color="var(--color-viewmodel)" />
            <h3 style={{ fontSize: '17px', fontWeight: 700 }}>Export as Apple Swift Test</h3>
          </div>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: 'var(--text-muted)', cursor: 'pointer' }}>
            <X size={18} />
          </button>
        </div>

        <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
          This standalone test suite was materialized from your verified canvas trace. Running <code>swift test</code> will execute this against the real Swift compiler and runtime.
        </div>

        <div style={{ background: 'rgba(0,0,0,0.4)', borderRadius: 8, padding: 12, border: '1px solid var(--border-subtle)', overflow: 'hidden' }}>
          <pre className="code-pre" style={{ maxHeight: 280, fontSize: '11px', color: '#38bdf8' }}>
            {generatedCode}
          </pre>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: 6 }}>
          <div style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
            Target: <code>{targetPath}</code>
          </div>

          <div style={{ display: 'flex', gap: 10 }}>
            <button className="btn-pill" onClick={handleCopy}>
              {copied ? <Check size={14} color="var(--color-success)" /> : <Copy size={14} />}
              <span>{copied ? 'Copied!' : 'Copy Code'}</span>
            </button>
            <button className="btn-pill primary" onClick={handleSaveToSuite} disabled={isSaving}>
              {saved ? <CheckCircle2 size={14} /> : <Download size={14} />}
              <span>{saved ? 'Saved to Test Suite!' : (isSaving ? 'Saving...' : 'Save to Test Suite')}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
