import Foundation
import SaagCore

public enum TestGenerator {

    public static func generateSwiftTest(for scenario: String, moduleName: String = "AuthSample") -> String {
        switch scenario.lowercased() {
        case "happy_path", "happy":
            return generateHappyPathTest(moduleName: moduleName)
        case "validation_error", "validation":
            return generateValidationErrorTest(moduleName: moduleName)
        case "auth_error", "auth":
            return generateAuthErrorTest(moduleName: moduleName)
        default:
            return generateGenericTest(scenario: scenario, moduleName: moduleName)
        }
    }

    private static func generateHappyPathTest(moduleName: String) -> String {
        return """
        // Auto-generated by SaaG (Software as a Graph)
        // Scenario: Happy Path Valid Login
        // Conforms to RFC-003 Dataflow Verification Specification

        import Testing
        import Foundation
        @testable import \(moduleName)

        @Suite("SaaG Dataflow: Happy Path Valid Login")
        struct SaagHappyPathDataflowTests {

            @Test("Verifies valid credentials propagate through LoginView -> AuthViewModel -> AuthService -> KeychainStorage")
            @MainActor
            func testHappyPathDataflow() async throws {
                // 1. Initial State & Component Graph Setup
                let mockService = LiveAuthService()
                let storage = KeychainStorage()
                let viewModel = AuthViewModel(authService: mockService, tokenStorage: storage)

                // 2. Input Injection at Port: login(credentials:)
                let inputPayload = Credentials(email: "alban@example.com", password: "password123")
                await viewModel.login(credentials: inputPayload)

                // 3. Node State Assertions derived from Graph Trace
                #expect(viewModel.isLoading == false, "ViewModel should finish in non-loading state")
                #expect(viewModel.errorMessage == nil, "No error message should be present on success")
                #expect(viewModel.activeSession != nil, "Active user session must be populated")
                #expect(viewModel.activeSession?.userId == "user_mock_42")

                // 4. Downstream Storage Node Assertion
                let savedToken = await storage.retrieve()
                #expect(savedToken == "jwt_mock_token_abc123", "KeychainStorage must contain the persisted session token")
            }
        }
        """
    }

    private static func generateValidationErrorTest(moduleName: String) -> String {
        return """
        // Auto-generated by SaaG (Software as a Graph)
        // Scenario: Validation Error Short Password
        // Conforms to RFC-003 Dataflow Verification Specification

        import Testing
        import Foundation
        @testable import \(moduleName)

        @Suite("SaaG Dataflow: Validation Error Short Password")
        struct SaagValidationErrorDataflowTests {

            @Test("Verifies password < 6 chars halts before AuthService and mutates errorMessage")
            @MainActor
            func testShortPasswordHaltsExecution() async throws {
                // 1. Initial State
                let storage = KeychainStorage()
                let viewModel = AuthViewModel(tokenStorage: storage)

                // 2. Input Injection: Short password
                let inputPayload = Credentials(email: "alban@example.com", password: "123")
                await viewModel.login(credentials: inputPayload)

                // 3. Branch Decision & State Mutation Assertions
                #expect(viewModel.errorMessage == "Password must be at least 6 characters.")
                #expect(viewModel.isLoading == false)
                #expect(viewModel.activeSession == nil, "No session should be created on validation failure")

                // 4. Verify Downstream Storage was NOT touched
                let savedToken = await storage.retrieve()
                #expect(savedToken == nil, "Storage must remain empty when flow halts at validation")
            }
        }
        """
    }

    private static func generateAuthErrorTest(moduleName: String) -> String {
        return """
        // Auto-generated by SaaG (Software as a Graph)
        // Scenario: Network Auth Failure 401
        // Conforms to RFC-003 Dataflow Verification Specification

        import Testing
        import Foundation
        @testable import \(moduleName)

        @Suite("SaaG Dataflow: Network Auth Failure 401")
        struct SaagAuthErrorDataflowTests {

            @Test("Verifies invalid credentials throw AuthError and branch to error handler")
            @MainActor
            func testInvalidCredentialsTriggersErrorBranch() async throws {
                let storage = KeychainStorage()
                let viewModel = AuthViewModel(tokenStorage: storage)

                // Input Injection: Wrong password triggers AuthService throw
                let inputPayload = Credentials(email: "alban@example.com", password: "wrongpass")
                await viewModel.login(credentials: inputPayload)

                #expect(viewModel.errorMessage == "Invalid email or password.")
                #expect(viewModel.isLoading == false)
                #expect(viewModel.activeSession == nil)

                let savedToken = await storage.retrieve()
                #expect(savedToken == nil)
            }
        }
        """
    }

    private static func generateGenericTest(scenario: String, moduleName: String) -> String {
        return """
        // Auto-generated by SaaG (Software as a Graph)
        import Testing
        @testable import \(moduleName)

        @Suite("SaaG Dataflow: \(scenario)")
        struct SaagGenericDataflowTests {
            @Test("Verifies dataflow for \(scenario)")
            func testDataflow() async throws {
                #expect(true)
            }
        }
        """
    }
}
